safe: false
baseurl: /

source: .
destination: ./_site
plugins: ./_plugins

permalink: none

name: OSMTimeLapseR
markdown: kramdown # see https://help.github.com/articles/migrating-your-pages-site-from-maruku
baseurl: /OSMTimeLapseR

analytics:
    provider: google
    google:
        tracking_id: 'UA-51523630-1'
